<script setup lang="ts">
import { ref } from 'vue';
import type { RoomSnapshot } from '../../../shared/protocol';
import type { Character, Color } from '../../../shared/game/types';
import { characterName, otherCharacter } from '../../../shared/game/types';
import CharacterArt from './CharacterArt.vue';
import AppIcon from '../common/AppIcon.vue';
interface Props { room: RoomSnapshot; color: Color; busy: boolean; connected: boolean; error: string }
const props = defineProps<Props>();
const emit = defineEmits<{ (event: 'ready'): void; (event: 'leave'): void; (event: 'character', character: Character): void }>();
const copied = ref(false);
async function copy(): Promise<void> { try { await navigator.clipboard.writeText(props.room.code); copied.value = true; } catch { copied.value = false; } }
</script>
<template><section class="lobby"><p class="eyebrow muted">A SEAT FOR YOUR FRIEND</p><h1>친구의 자리를 비워뒀어요.</h1><p class="lobby-description">같은 주소에 접속한 친구에게 아래 코드를 알려주세요.</p><button class="room-code" aria-label="방 코드 복사" @click="copy">{{ room.code }}<AppIcon name="copy" /></button><p class="copy-note">{{ copied ? '방 코드를 복사했어요!' : '코드를 누르면 복사돼요' }}</p><div class="lobby-players"><div v-for="side in ['black', 'white'] as const" :key="side" class="lobby-player"><div class="lobby-art"><CharacterArt :character="side === 'black' ? room.settings.blackCharacter : otherCharacter(room.settings.blackCharacter)" /></div><h2>{{ characterName(side === 'black' ? room.settings.blackCharacter : otherCharacter(room.settings.blackCharacter)) }} <span>{{ color === side ? '나' : '친구' }}</span></h2><p>{{ !room.players.find(p => p.color === side) ? '친구를 기다리는 중…' : !room.players.find(p => p.color === side)?.connected ? '다시 연결하는 중…' : room.players.find(p => p.color === side)?.ready ? '준비 완료 ✓' : '입장 완료' }}</p></div></div><button class="secondary swap-character" :disabled="busy || !connected || room.players.some(p => p.ready)" @click="emit('character', color === 'black' ? otherCharacter(room.settings.blackCharacter) : room.settings.blackCharacter)">캐릭터 서로 바꾸기</button><div class="lobby-settings">{{ room.settings.seconds ? `한 수 ${room.settings.seconds}초` : '시간 제한 없음' }} · 흑돌 선공 · 무르기 없음</div><button class="primary" :disabled="busy || !connected || room.players.find(p => p.color === color)?.ready" @click="emit('ready')">{{ room.players.find(p => p.color === color)?.ready ? '상대의 준비를 기다리는 중…' : '준비 완료' }}</button><button class="text-button" @click="emit('leave')">방 나가기</button><p v-if="error" role="alert" class="lobby-error">{{ error }}</p></section></template>
<style scoped lang="scss">
.lobby { max-width: 600px; margin: 50px auto; text-align: center; background: var(--card); border: 1px solid var(--line); border-radius: var(--radius); padding: 40px 24px; }h1 { font-size: clamp(24px, 4vw, 32px); letter-spacing: -.05em; margin: 15px 0; }.lobby-description { color: var(--muted); font-size: var(--text-small); line-height: 1.7; }.room-code { font-family: ui-monospace, monospace; font-size: 30px; letter-spacing: .15em; display: inline-flex; gap: 20px; align-items: center; background: #eef1e2; border: 1px dashed #b1bf95; border-radius: 12px; padding: 18px 22px; margin-top: 25px; user-select: all; }.copy-note { margin-top: 9px; color: var(--muted); font-size: var(--text-caption); }.lobby-players { display: flex; justify-content: center; gap: 38px; margin: 25px 0; }.lobby-art { width: 115px; height: 115px; margin: auto; }h2 { font-size: 17px; }h2 span { color: var(--muted); font-size: var(--text-caption); font-weight: 400; }.lobby-player > p { color: var(--text-accent); font-size: var(--text-small); margin-top: 8px; }.swap-character { font-size: var(--text-small); }.lobby-settings { color: var(--muted); font-size: var(--text-small); margin: 24px 0; }.primary { display: flex; width: min(320px, 100%); margin: 0 auto 12px; }.lobby-error { color: var(--danger); font-size: var(--text-small); }
</style>
